title: Relay Docs
description: Public Documentation for relay.fyi
theme: just-the-docs

url: https://docs.relay.fyi

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Add to Slack: https://app.relay.fyi/slack/install
search_enabled: true
